name: Test Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print which secrets are set
        run: |
          echo "TWITTER_API_KEY is ${TWITTER_API_KEY:+✅ set}"
          echo "TWITTER_API_SECRET is ${TWITTER_API_SECRET:+✅ set}"
          echo "TWITTER_ACCESS_TOKEN is ${TWITTER_ACCESS_TOKEN:+✅ set}"
          echo "TWITTER_ACCESS_SECRET is ${TWITTER_ACCESS_SECRET:+✅ set}"
          echo "BEARER_TOKEN is ${BEARER_TOKEN:+✅ set}"
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
